services:
    app-blue:
        image: ghcr.io/fisherbyu/a-fisher-web-site:latest
        ports:
            - '3000:3000'
        env_file:
            - /srv/a-fisher-web-site/.env
        restart: unless-stopped

    app-green:
        image: ghcr.io/fisherbyu/a-fisher-web-site:latest
        ports:
            - '3001:3000'
        env_file:
            - /srv/a-fisher-web-site/.env
        restart: unless-stopped
