services:
    app-blue:
        image: ghcr.io/fisherbyu/a-fisher-web-site:latest
        ports:
            - '3000:3000'
        env_file:
            - /srv/your-site/.env.production # lives on the server, never in the repo
        volumes:
            # Only needed if you go with Option B for file assets
            # - /srv/your-site/uploads:/app/public/uploads
        restart: unless-stopped

    app-green:
        image: ghcr.io/fisherbyu/a-fisher-web-site:latest
        ports:
            - '3001:3000'
        env_file:
            - /srv/your-site/.env
        volumes:
            # - /srv/your-site/uploads:/app/public/uploads
        restart: unless-stopped
